#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
set -Eeuo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INCREMENTAL=false
SKIP_DEPS=false
DOWNLOAD_ATTEMPTS="${B2Q_DOWNLOAD_ATTEMPTS:-3}"
DOWNLOAD_RETRY_DELAY="${B2Q_DOWNLOAD_RETRY_DELAY:-15}"
VERSION_CONNECT_TIMEOUT="${B2Q_VERSION_CONNECT_TIMEOUT:-30}"
VERSION_READ_TIMEOUT="${B2Q_VERSION_READ_TIMEOUT:-60}"

usage() {
    cat <<'USAGE'
Usage: scripts/build_b2q.sh [--incremental] [--skip-deps]

Environment:
  B2Q_TARGET_FIRMWARE="SM-F711B/EUX/<FULL_IMEI_OR_SERIAL>"
      Target firmware used while UN1CA generates out/config.sh. SOURCE_FIRMWARE
      stays untouched and comes from upstream unica/configs/qssi.sh.
  B2Q_DOWNLOAD_ATTEMPTS=3
      Number of attempts for the standard UN1CA download_fw step.
  B2Q_DOWNLOAD_RETRY_DELAY=15
      Base delay in seconds; later attempts use a multiplied delay.
  B2Q_VERSION_CONNECT_TIMEOUT=30
  B2Q_VERSION_READ_TIMEOUT=60
      Connect/read timeout used by samloader for version.xml.

The wrapper keeps UN1CA's standard download_fw implementation. It validates
and downloads the target first, then the qssi donor, so a rejected FUS identity
is detected before a multi-gigabyte donor download begins. Each stage is retried
up to three times, then firmware is extracted, audited and passed to make_rom.
USAGE
}

require_positive_int() {
    local name=$1 value=$2
    if [[ ! "$value" =~ ^[1-9][0-9]*$ ]]; then
        echo "$name must be a positive integer, got: $value" >&2
        exit 2
    fi
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --incremental) INCREMENTAL=true ;;
        --skip-deps) SKIP_DEPS=true ;;
        -h|--help) usage; exit 0 ;;
        *) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
    esac
    shift
done

require_positive_int B2Q_DOWNLOAD_ATTEMPTS "$DOWNLOAD_ATTEMPTS"
require_positive_int B2Q_DOWNLOAD_RETRY_DELAY "$DOWNLOAD_RETRY_DELAY"
require_positive_int B2Q_VERSION_CONNECT_TIMEOUT "$VERSION_CONNECT_TIMEOUT"
require_positive_int B2Q_VERSION_READ_TIMEOUT "$VERSION_READ_TIMEOUT"

cd "$ROOT"
export SRC_DIR="$ROOT"
"$ROOT/scripts/validate_b2q.sh"
# shellcheck disable=SC1091
source "$ROOT/buildenv.sh" b2q

# Keep SOURCE_FIRMWARE exactly as generated by upstream qssi. The target gets
# B2Q_TARGET_FIRMWARE through target/b2q/config.sh, then UN1CA's original
# download_fw.sh parses and downloads both tuples independently.
$SKIP_DEPS || run_cmd build_dependencies

# Upstream currently patches samloader's version.xml request with a 3-second
# timeout. Retain samloader and the original download_fw flow, but use a more
# realistic connect/read timeout for desktop networks.
python3 "$ROOT/scripts/tune_b2q_samloader.py" \
    "$TOOLS_DIR/venv" "$VERSION_CONNECT_TIMEOUT" "$VERSION_READ_TIMEOUT"

version_xml_preflight() {
    local firmware=$1 model csc _identity url
    IFS=/ read -r model csc _identity <<<"$firmware"
    [[ -n "$model" && -n "$csc" ]] || return 1
    url="https://fota-cloud-dn.ospserver.net/firmware/$csc/$model/version.xml"

    local extra_retry=()
    if curl --help all 2>/dev/null | grep -q -- '--retry-all-errors'; then
        extra_retry+=(--retry-all-errors)
    fi
    curl --fail --silent --show-error --location \
        --user-agent 'Kies2.0_FUS' \
        --connect-timeout "$VERSION_CONNECT_TIMEOUT" \
        --max-time "$VERSION_READ_TIMEOUT" \
        --retry 3 --retry-delay 2 "${extra_retry[@]}" \
        --output /dev/null "$url"
}


print_samloader_diagnostics() {
    local found=false f
    while IFS= read -r f; do
        found=true
        echo "--- samloader diagnostics: ${f#"$ROOT/"} ---" >&2
        tail -n 100 "$f" >&2 || true
    done < <(find "$OUT_DIR" -maxdepth 2 -type f \
        \( -iname 'samloader.log' -o -iname '*samloader*.log' \) \
        -mmin -15 -print 2>/dev/null | sort)
    $found || true
}

cleanup_incomplete_download() {
    local firmware=$1 model csc _identity dir
    IFS=/ read -r model csc _identity <<<"$firmware"
    [[ -n "$model" && -n "$csc" ]] || return 0
    dir="$ODIN_DIR/${model}_${csc}"
    if [[ -d "$dir" && ! -f "$dir/.downloaded" ]]; then
        echo "- Removing incomplete firmware download: ${dir#"$ROOT/"}"
        rm -rf "$dir"
    fi
}

download_firmware_stage() {
    local label=$1 firmware=$2 ignore_flag=$3
    local attempt rc delay
    for ((attempt = 1; attempt <= DOWNLOAD_ATTEMPTS; attempt++)); do
        echo "- ${label} firmware download attempt $attempt/$DOWNLOAD_ATTEMPTS"
        if run_cmd download_fw "$ignore_flag"; then
            return 0
        else
            rc=$?
            print_samloader_diagnostics
        fi
        if (( attempt == DOWNLOAD_ATTEMPTS )); then
            echo "${label^} firmware download failed after $DOWNLOAD_ATTEMPTS attempts." >&2
            return "$rc"
        fi
        cleanup_incomplete_download "$firmware"
        delay=$((DOWNLOAD_RETRY_DELAY * attempt))
        echo "- ${label^} download failed; retrying in ${delay}s..." >&2
        sleep "$delay"
    done
}

# A preflight GET does not replace samloader; it only catches DNS/TLS/server
# reachability issues before a multi-gigabyte download begins.
version_xml_preflight "$TARGET_FIRMWARE" \
    || echo "Warning: target version.xml preflight failed; download_fw will retry." >&2
version_xml_preflight "$SOURCE_FIRMWARE" \
    || echo "Warning: donor version.xml preflight failed; download_fw will retry." >&2

# Use UN1CA's own download_fw for both stages. Target goes first so an invalid
# IMEI/serial is rejected before the much larger qssi donor is downloaded.
download_firmware_stage "target" "$TARGET_FIRMWARE" --ignore-source
download_firmware_stage "source" "$SOURCE_FIRMWARE" --ignore-target

cleanup_incomplete_extract() {
    local firmware model csc _identity dir
    for firmware in "$TARGET_FIRMWARE" "$SOURCE_FIRMWARE"; do
        IFS=/ read -r model csc _identity <<<"$firmware"
        [[ -n "$model" && -n "$csc" ]] || continue
        dir="$FW_DIR/${model}_${csc}"
        if [[ -d "$dir" && ! -f "$dir/.extracted" ]]; then
            echo "- Removing incomplete firmware extraction: ${dir#"$ROOT/"}"
            rm -rf "$dir" 2>/dev/null || sudo rm -rf "$dir"
        fi
    done
}

# A failed sudo prompt or interrupted mount can leave a half-extracted tree.
# Remove only directories without the upstream .extracted completion marker;
# downloaded Odin archives are retained and will not be fetched again.
cleanup_incomplete_extract
run_cmd extract_fw

TARGET_FIRMWARE_PATH="$(cut -d/ -f1,2 <<<"$TARGET_FIRMWARE" | tr / _)"
TARGET_FIRMWARE_DIR="$FW_DIR/$TARGET_FIRMWARE_PATH"
if [[ ! -d "$TARGET_FIRMWARE_DIR" ]]; then
    echo "Extracted target firmware directory not found: $TARGET_FIRMWARE_DIR" >&2
    exit 1
fi
"$ROOT/scripts/prepare_b2q_camera.sh" "$TARGET_FIRMWARE_DIR"
"$ROOT/scripts/prepare_b2q_dvfs.sh" "$TARGET_FIRMWARE_DIR" \
    "$TARGET_DVFSAPP_CONFIG_SSRM_POLICY_FILENAME" \
    "$TARGET_DVFSAPP_CONFIG_DVFS_POLICY_FILENAME"
"$ROOT/scripts/prepare_b2q_overlay.sh" "$TARGET_FIRMWARE_DIR"
"$ROOT/scripts/prepare_b2q_vintf.sh" "$TARGET_FIRMWARE_DIR"
"$ROOT/scripts/audit_b2q_firmware.sh" "$TARGET_FIRMWARE_DIR"

AOD_INPUT_APPLIED=false
restore_b2q_aod_input() {
    if $AOD_INPUT_APPLIED; then
        "$ROOT/scripts/prepare_b2q_aod.sh" "$TARGET_FIRMWARE_DIR" restore || true
    fi
}
trap restore_b2q_aod_input EXIT INT TERM
"$ROOT/scripts/prepare_b2q_aod.sh" "$TARGET_FIRMWARE_DIR" apply
AOD_INPUT_APPLIED=true

B2Q_DIMENS="$ROOT/target/b2q/overlay/dimens.xml"
if [[ -f "$B2Q_DIMENS" ]]; then
    echo "- Final b2q power-button resource before make_rom:"
    grep -E 'physical_power_button_center_screen_location_y' "$B2Q_DIMENS" || true
fi
"$ROOT/scripts/prepare_b2q_aod.sh" "$TARGET_FIRMWARE_DIR" status

if $INCREMENTAL; then
    run_cmd make_rom --build-rom-zip
else
    run_cmd make_rom --force --build-rom-zip
fi

restore_b2q_aod_input
AOD_INPUT_APPLIED=false
trap - EXIT INT TERM
